import turtle
lengthSide = turtle.numinput('','Enter a number: ')

def drawsquare(arg):
    turtle.forward(int(arg))
    turtle.left(90)
    turtle.forward(int(arg))
    turtle.left(90)
    turtle.forward(int(arg))
    turtle.left(90)
    turtle.forward(int(arg))
    turtle.left(90)

#call drawsquare
drawsquare(lengthSide)
turtle.left(30)
drawsquare(lengthSide)
turtle.left(30)
drawsquare(lengthSide)
turtle.left(30)
drawsquare(lengthSide)
turtle.left(30)
drawsquare(lengthSide)
turtle.left(30)
drawsquare(lengthSide)
turtle.left(30)
drawsquare(lengthSide)
turtle.left(30)
drawsquare(lengthSide)
turtle.left(30)
drawsquare(lengthSide)
turtle.left(30)
drawsquare(lengthSide)
turtle.left(30)
drawsquare(lengthSide)
turtle.left(30)
drawsquare(lengthSide)
turtle.left(30)
